
package com.t_voigt.bendprep;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.StringTokenizer;
/**
 *
 * @author timo
 */
public class BendPrepGui extends javax.swing.JDialog {

    /**
     * Creates new form BendPrepGui
     */
    public BendPrepGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TextAreaOutputStream textOut = new TextAreaOutputStream(log);
        PrintStream outStream = new PrintStream(textOut, true);
        System.setOut(outStream);
        System.setErr(outStream);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourcePath = new javax.swing.JTextField();
        browseSource = new javax.swing.JButton();
        browseParam = new javax.swing.JButton();
        paramPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bendColor = new javax.swing.JTextField();
        cutColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        offset = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        focusHeight = new javax.swing.JTextField();
        accuracy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        xdiv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ydiv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sourcePath.setText("path to file...");
        sourcePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourcePathMouseClicked(evt);
            }
        });
        sourcePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourcePathActionPerformed(evt);
            }
        });

        browseSource.setText("Browse...");
        browseSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSourceActionPerformed(evt);
            }
        });

        browseParam.setText("Browse...");
        browseParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseParamActionPerformed(evt);
            }
        });

        paramPath.setText("path to file...");
        paramPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paramPathMouseClicked(evt);
            }
        });
        paramPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramPathActionPerformed(evt);
            }
        });

        jLabel1.setText("source file location");

        jLabel2.setText("parameter file location");

        jLabel3.setText("Welcome to BendPrep! Please enter file locations below:");

        log.setEditable(false);
        log.setColumns(15);
        log.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setText("bendColor");

        jLabel6.setText("cutColor");

        bendColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bendColorActionPerformed(evt);
            }
        });

        cutColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutColorActionPerformed(evt);
            }
        });

        jLabel7.setText("offset");

        offset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offsetActionPerformed(evt);
            }
        });

        jLabel8.setText("focusHeight");

        focusHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                focusHeightActionPerformed(evt);
            }
        });

        accuracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accuracyActionPerformed(evt);
            }
        });

        jLabel9.setText("accuracy");

        xdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xdivActionPerformed(evt);
            }
        });

        jLabel10.setText("xdiv");

        jLabel11.setText("ydiv");

        ydiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ydivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(closeButton)
                            .addGap(303, 303, 303)
                            .addComponent(startButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sourcePath, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(paramPath)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(offset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bendColor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cutColor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(focusHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ydiv, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseParam)
                            .addComponent(browseSource))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseSource)
                    .addComponent(sourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paramPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(browseParam, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(bendColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xdiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cutColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ydiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(focusHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(closeButton))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourcePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourcePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourcePathActionPerformed

    private void paramPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramPathActionPerformed

    private void browseSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSourceActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileNameExtensionFilter("SVG File","svg");
        int returnVal = fc.showOpenDialog(BendPrepGui.this); //Where frame is the parent component
        
        java.io.File file = null;
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            sourcePath.setText(path);
            //Now you have your file to do whatever you want to do
        } else {
            //User did not choose a valid file
            log.append("invalid source file\n");
        }
    }//GEN-LAST:event_browseSourceActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        if(sourcePath.getText().equals("path to file...")) {
            System.out.println("Please specify source file path first");
        } else if ((paramPath.getText().equals("path to file...") || paramPath.getText().isEmpty()) && 
                (bendColor.getText().isEmpty() || cutColor.getText().isEmpty() || offset.getText().isEmpty() ||
                focusHeight.getText().isEmpty() || accuracy.getText().isEmpty() || xdiv.getText().isEmpty() ||
                ydiv.getText().isEmpty())) {
            System.out.println("Please specify Parameters first!");
        } else {
            if (!paramPath.getText().equals("path to file...")) {
                if (bendColor.getText().isEmpty() || cutColor.getText().isEmpty() || offset.getText().isEmpty() ||
                focusHeight.getText().isEmpty() || accuracy.getText().isEmpty() || xdiv.getText().isEmpty() ||
                ydiv.getText().isEmpty()) {
                    ParameterDummy dummy = new ParameterDummy(bendColor.getText(), cutColor.getText(), Double.parseDouble(offset.getText()),
                    Double.parseDouble(focusHeight.getText()), Double.parseDouble(accuracy.getText()), Double.parseDouble(xdiv.getText()), 
                    Double.parseDouble(ydiv.getText()));
                    BendPrep.prep(sourcePath.getText(), null, dummy);
                } else {
                    BendPrep.prep(sourcePath.getText(), paramPath.getText(), null);
                }
            } else {
                ParameterDummy dummy = new ParameterDummy(bendColor.getText(), cutColor.getText(), Double.parseDouble(offset.getText()),
                Double.parseDouble(focusHeight.getText()), Double.parseDouble(accuracy.getText()), Double.parseDouble(xdiv.getText()), 
                Double.parseDouble(ydiv.getText()));
                BendPrep.prep(sourcePath.getText(), null, dummy);
            }
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void browseParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseParamActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        int returnVal = fc.showOpenDialog(BendPrepGui.this); //Where frame is the parent component

        java.io.File file = null;
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            paramPath.setText(path);
            try {
                fillParamFields(path);
            } catch (IOException e) {}
            //Now you have your file to do whatever you want to do
        } else {
            //User did not choose a valid file
            log.append("invalid parameter file\n");
        }
    }//GEN-LAST:event_browseParamActionPerformed

    private void fillParamFields(String configfile) throws IOException{
        FileReader fr = new FileReader(configfile);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(line);
                String type = (String) st.nextElement();
                String value = (String) st.nextElement();
                //System.out.println(type + " " + value);
                switch (type) {
                    case "bendColor":   bendColor.setText(value);
                                        break;
                    case "cutColor":    cutColor.setText(value);
                                        break;
                    case "offset":      offset.setText(value);
                                        break;
                    case "focusHeight": focusHeight.setText(value);
                                        break;
                    case "accuracy":    accuracy.setText(value);
                                        break;
                    case "xdiv":        xdiv.setText(value);
                                        break;
                    case "ydiv":        ydiv.setText(value);
                                        break;
                }
            }
    }
    private void paramPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paramPathMouseClicked
        // TODO add your handling code here:
        if(countP == 0) {
            paramPath.setText("");
            countP++;
        }
    }//GEN-LAST:event_paramPathMouseClicked

    private void sourcePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourcePathMouseClicked
        // TODO add your handling code here:
        if(countS == 0) {
            sourcePath.setText("");
            countS++;
        }
    }//GEN-LAST:event_sourcePathMouseClicked

    private void bendColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bendColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bendColorActionPerformed

    private void cutColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutColorActionPerformed

    private void offsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offsetActionPerformed

    private void focusHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focusHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_focusHeightActionPerformed

    private void accuracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accuracyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accuracyActionPerformed

    private void xdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xdivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xdivActionPerformed

    private void ydivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ydivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ydivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BendPrepGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BendPrepGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BendPrepGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BendPrepGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BendPrepGui dialog = new BendPrepGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private int countP = 0;
    private int countS = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accuracy;
    private javax.swing.JTextField bendColor;
    private javax.swing.JButton browseParam;
    private javax.swing.JButton browseSource;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField cutColor;
    private javax.swing.JTextField focusHeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea log;
    private javax.swing.JTextField offset;
    private javax.swing.JTextField paramPath;
    private javax.swing.JTextField sourcePath;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField xdiv;
    private javax.swing.JTextField ydiv;
    // End of variables declaration//GEN-END:variables
}
